## Understanding the Data

In [19]:
import pandas as pd

csv=pd.read_csv('data/c-test-ds.csv')

pd.set_option('display.max_columns', None) # Prevent columns from being hidden
pd.set_option('display.width', 1000)        # Give the text output a wider area before it wraps

### Check dataset shape

In [20]:
print("Dataset shape:", csv.shape)

Dataset shape: (418, 13)

### Display column data types.

In [21]:
csv.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Date            object
dtype: object

### Identify numerical and categorical columns

In [22]:
numerical_columns = csv.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = csv.select_dtypes(include=['object']).columns

print("\nNumerical columns:", list(numerical_columns))
print("Categorical columns:", list(categorical_columns))

Numerical columns: ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
Categorical columns: ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Date']

### Checking missing values count per column.

In [23]:
csv.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Date             0
dtype: int64

### Some other techniques

In [24]:
print("\n using describe()")
csv.describe()

 using describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    0.363636    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.481622    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    0.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    0.000000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    0.000000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    1.000000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    1.000000    3.000000   76.000000    8.000000    9.000000  512.329200

### Describ with conditional

In [25]:

csv.describe(include=['object'])

                    Name   Sex    Ticket            Cabin Embarked        Date
count                418   418       418               91      418         418
unique               418     2       363               76        3         342
top     Kelly, Mr. James  male  PC 17608  B57 B59 B63 B66        S  2025-06-12
freq                   1   266         5                3      270           4

### using head() and tail()

In [26]:
csv.head(5)
csv.tail(5)

     PassengerId  Survived  Pclass                          Name     Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked        Date
413         1305         0       3            Spector, Mr. Woolf    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  2023-02-25
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female  39.0      0      0            PC 17758  108.9000  C105        C  2024-06-17
415         1307         0       3  Saether, Mr. Simon Sivertsen    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  2025-02-27
416         1308         0       3           Ware, Mr. Frederick    male   NaN      0      0              359309    8.0500   NaN        S  2023-12-03
417         1309         0       3      Peter, Master. Michael J    male   NaN      1      1                2668   22.3583   NaN        C  2023-08-19

### change float64 to float32 and display the info

In [27]:
csv.info()
print("\n Changed float64 to float32 ")
csv = csv.astype({col: 'float32' for col in numerical_columns if csv[col].dtype == 'float64'})
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
 12  Date         418 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 42.6+ KB

 Changed float64 to float32
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float32
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float32
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
 12  Date         418 non-null    object
dtypes: float32(2), int64(5), object(6)
memory usage: 39.3+ KB